version: "3.8"
services:
  sample_db-postgresql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
    volumes:
      - sample_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  sample_db:
